language: r

install:
  - R -e "install.packages('devtools')"
  - R -e "devtools::install_github('rstudio/rmarkdown')"
  
script:
  - R -e "rmarkdown::render('NicholasClarkCV.Rmd')"
  - R -e "rmarkdown::render('README.Rmd')"

after_success:
  - git add --all *
  - git commit -m"Daily update"
  - git push -q https://${GITHUB_PAT}@github.com/${TRAVIS_REPO_SLUG}.git HEAD:master
